export const Routing = {
  HOME: '/',
  ABOUT: '/about',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  JOBS: '/jobs',
  TERMS: '/terms',
  RENTALS: '/rentals',
  RESERVATION: '/reservation',
  TICKETS: '/tickets',
  SETTINGS: '/settings',
  ADMIN: '/admin/movies',
  WISHLIST: '/wishlist',
  ADMIN_TICKETS: '/admin/tickets',
  ADMIN_USERS: '/admin/users',
  CHECKOUT: '/checkout',
  SUCCESS: '/success',
  NEW_MOVIE: '/admin/new-movie',
  HALLS: '/admin/halls',
  UPDATE_HALL: '/admin/update-hall',
  REPERTOIRE: '/admin/repertoire',
  PROMO_CODES: '/admin/promo-codes',
  NEWSLETTER: '/admin/newsletter',
}
